# _____     _              ___  ___                 _     _           _ _            
#|  ___|   | |             |  \/  |                | |   (_)         (_) |           
#| |____  _| |_ _ __ __ _  | .  . | __ _  ___ ___  | |    _ _ __ ___  _| |_ ___ _ __ 
#|  __\ \/ / __| '__/ _` | | |\/| |/ _` |/ __/ _ \ | |   | | '_ ` _ \| | __/ _ \ '__|
#| |___>  <| |_| | | (_| | | |  | | (_| | (_|  __/ | |___| | | | | | | | ||  __/ |   
#\____/_/\_\\__|_|  \__,_| \_|  |_/\__,_|\___\___| \_____/_|_| |_| |_|_|\__\___|_|   
#                                                                                    
#                                                                                    
# Extra Mace Limiter Configuration
# Advanced mace management plugin with configurable limits and storage restrictions
# Author: notauthorised
# Discord: https://discord.gg/hBD2psrM6t


# Maximum number of maces a player can have in their inventory at once
# Set to -1 for unlimited maces
# Default: 2 (players can carry up to 2 maces)
max-maces-in-inventory: 2

# Prevent players from picking up maces when they have reached the limit
# true = block pickup when at max maces (recommended)
# false = allow pickup even at max maces (basically turning this feature off)
stop-pickup-at-max-maces: true



# which storage blocks can maces be placed in
# Set to true to block maces, false to allow maces to be put in it.

blocked-storages:
  # Regular chests (including chest boats and minecart chests)
  chest: true
  
  # Ender chests
  ender-chest: true
  
  # Barrels 
  barrel: true
  
  # Shulker boxes 
  shulker-box: true
  
  # Hoppers
  hopper: true
  
  # Droppers 
  dropper: true
  
  # Dispensers 
  dispenser: true
  
  # Furnaces 
  furnace: true
  
  # Blast furnaces 
  blast-furnace: true
  
  # Smokers
  smoker: true
  
  # Auto crafters 
  crafter: true


# Prevent hoppers from picking up maces from the ground
# true = block hopper pickup maces (recommended)
# false = allow hopper pickup maces
block-hopper-pickup: true

# Prevent hopper minecarts from picking up maces
# true = block hopper minecart pickup (recommended)  
# false = allow hopper minecart pickup
block-hopper-minecart-pickup: true

# Prevent placing maces in item frames (including glow item frames)
# true = block item frame placement (recommended)
# false = allow item frame placement
block-item-frame-placement: true

# Prevent bundles containing maces from being placed in blocked inventories
# true = block bundles with maces (recommended)
# false = allow bundles with maces
block-bundles-with-maces: true


# Warning messages (i made these look similar to worldguard messages)
messages:
  # Storage blocking messages (when trying to place maces in blocked inventories or item frames)
  storage-blocking:
    # Show message on first attempt, then every %frequency% attempts after
    frequency: 5

    text: "&c&lHey! &7You can't move a mace outside your inventory."
  
  # Pickup blocking messages (when trying to pick up maces at max limit)
  pickup-blocking:
    # Show message on first attempt, then every %frequency% attempts after
    frequency: 100

    text: "&c&lHey! &7You can't carry more than 2 maces at once."


debug: false

config-version: 1